### ISSUE TITLE
Component values

### ISSUE THREAD

**Issue by jahquubel** [tarori/Circuit.USB-DAC#1]
![image](https://github.com/user-attachments/assets/6214ee72-d33b-43d5-8581-43e4ad7221a5)
Hello thanks for sharing this schematic.

What are the  of the component values around  ADA4075 or what  DNP, CMP or FF means here?

**Comment by tarori** [comment]
They are tuning knobs for high frequency characteristics.
I don't populate components for these DNP/CMP/FF, with ADA4075 or OPA1656. But if you use a very high-performance opamp, like LME49990, you may need to put 10pF-100pF capacitor at CMP or FF, to prevent oscillation.

**Comment by jahquubel** [comment]
Got it thanks ! 

I am trying to modify it with ADA4075 as the output without amplification. 
I will leave r43 and just check designs, maybe just short ff and take output from R23.
